# Generated by Django 4.2.11 on 2024-05-30 22:50

from django.db import migrations, models

def add_reviews(apps, schema_editor):
    Movie = apps.get_model("movies", "Movie")
    Review = apps.get_model("movies", "Review")
    db_alias = schema_editor.connection.alias

    # Add reviews for Forrest Gump
    forrest_gump = Movie.objects.using(db_alias).get(id=1)
    Review.objects.using(db_alias).bulk_create([
        Review(movie=forrest_gump, reviewer_name="Basit Zahid", rating=4),
        Review(movie=forrest_gump, reviewer_name="Chrissa Loth", rating=3)
    ])

    # Add reviews for Toy Story
    toy_story = Movie.objects.using(db_alias).get(id=2)
    Review.objects.using(db_alias).bulk_create([
        Review(movie=toy_story, reviewer_name="Reviewer 1", rating=5),
        Review(movie=toy_story, reviewer_name="Reviewer 2", rating=4)
    ])

    # Add reviews for Captain Phillips
    captain_phillips = Movie.objects.using(db_alias).get(id=3)
    Review.objects.using(db_alias).bulk_create([
        Review(movie=captain_phillips, reviewer_name="Reviewer 3", rating=4),
        Review(movie=captain_phillips, reviewer_name="Reviewer 4", rating=5)
    ])

    # Add reviews for Catch Me If You Can
    catch_me_if_you_can = Movie.objects.using(db_alias).get(id=4)
    Review.objects.using(db_alias).bulk_create([
        Review(movie=catch_me_if_you_can, reviewer_name="Reviewer 5", rating=4),
        Review(movie=catch_me_if_you_can, reviewer_name="Reviewer 6", rating=5)
    ])

    # Add reviews for Bridge of Spies
    bridge_of_spies = Movie.objects.using(db_alias).get(id=5)
    Review.objects.using(db_alias).bulk_create([
        Review(movie=bridge_of_spies, reviewer_name="Reviewer 7", rating=4),
        Review(movie=bridge_of_spies, reviewer_name="Reviewer 8", rating=5)
    ])

def remove_reviews(apps, schema_editor):
    Review = apps.get_model("movies", "Review")
    db_alias = schema_editor.connection.alias

    # Remove all reviews
    Review.objects.using(db_alias).filter(reviewer_name__in=[
        "Roger Ebert", "Gene Siskel", "Reviewer 1", "Reviewer 2", 
        "Reviewer 3", "Reviewer 4", "Reviewer 5", "Reviewer 6",
        "Reviewer 7", "Reviewer 8"
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_review"),
    ]
    
    operations = [migrations.RunPython(add_reviews, remove_reviews)]
